DROP DATABASE IF EXISTS pubs;

CREATE DATABASE pubs CHARACTER SET=utf8mb4 COLLATE utf8mb4_unicode_520_ci;
USE pubs;

CREATE TABLE localidad(
    codLocalidad INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE empleado(
    dniEmpleado VARCHAR(9) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    domicilio VARCHAR(255)
)ENGINE=InnoDB;

CREATE TABLE pub(
    codPub VARCHAR(30) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    licenciaFiscal VARCHAR(30) NOT NULL,
    domicilio VARCHAR(255),
    fechaApertura DATE NOT NULL,
    horario ENUM('HOR1','HOR2','HOR3') NOT NULL,
    codLocalidad INT UNSIGNED NOT NULL
)ENGINE=InnoDB;

CREATE TABLE pub_empleado(
    codPub VARCHAR(30),
    dniEmpleado VARCHAR(9),
    funcion ENUM('CAMARERO','SEGURIDAD','LIMPIEZA') NOT NULL,
    PRIMARY KEY(codPub,dniEmpleado,funcion)
)ENGINE=InnoDB;

CREATE TABLE titular(
    dniTitular VARCHAR(9) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    domicilio VARCHAR(255),
    codPub VARCHAR(30) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE existencias(
    codArticulo VARCHAR(30) PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    cantidad INT UNSIGNED NOT NULL,
    precio DECIMAL(8,2) UNSIGNED NOT NULL CHECK(precio > 0),
    codPub VARCHAR(30) NOT NULL
)ENGINE=InnoDB;

ALTER TABLE pub
    ADD FOREIGN KEY(codLocalidad) REFERENCES localidad(codLocalidad) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE pub_empleado
    ADD FOREIGN KEY(codPub) REFERENCES pub(codPub) ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD FOREIGN KEY(dniEmpleado) REFERENCES empleado(dniEmpleado) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE titular
    ADD FOREIGN KEY(codPub) REFERENCES pub(codPub) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE existencias
    ADD FOREIGN KEY(codPub) REFERENCES pub(codPub) ON DELETE RESTRICT ON UPDATE CASCADE;